[package]
name = "rust_tcp_reload"
version = "0.1.0"
authors = ["xinyi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
signal-hook = "0.3.8"
futures = { version = "0.3.14", features = ["thread-pool"] }